import { extractFeatures } from './featureEngine';

/**
 * Model configuration - these thresholds are derived from training
 * Run model/train.py to regenerate based on your dataset
 * 
 * Classification uses Decision Tree logic trained on K-Means clusters
 */
const MODEL_CONFIG = {
  // Default thresholds (will be updated after training)
  thresholds: {
    consistent: {
      cv_max: 0.55,    // Coefficient of variation threshold
      std_max: 28      // Standard deviation threshold
    },
    last_minute: {
      pi_min: 0.45,    // Procrastination index threshold
      trend_min: 8     // Minimum upward trend
    }
  }
};

/**
 * Load trained model configuration from JSON file
 * This is generated by the Python training script
 */
export async function loadModelConfig() {
  try {
    const response = await fetch('/model_config.json');
    if (response.ok) {
      const config = await response.json();
      Object.assign(MODEL_CONFIG, config);
      console.log('Loaded trained model config:', MODEL_CONFIG);
      return true;
    }
  } catch (e) {
    console.log('Using default model config (run train.py to generate trained config)');
  }
  return false;
}

/**
 * Classify a student's study pattern based on trained model rules
 * Uses Decision Tree logic derived from K-Means clustering
 * 
 * @param {Array} days - Array of 5 study minutes values
 * @returns {Object} Classification result with pattern, features, and reasoning
 */
export function classifyStudent(days) {
  const features = extractFeatures(days);
  const { cv_max, std_max } = MODEL_CONFIG.thresholds.consistent;
  const { pi_min, trend_min } = MODEL_CONFIG.thresholds.last_minute;
  
  let pattern = '';
  let reasoning = '';
  let confidence = '';

  // Decision Tree Classification Logic (trained from data)
  // Priority: Check for Last-minute first (stronger signal), then Consistent
  
  if (features.PI >= pi_min && features.trend >= trend_min) {
    // Last-minute: High concentration at end + upward trend
    pattern = 'Last-minute';
    reasoning = `Procrastination Index (${features.PI}) >= ${pi_min} AND trend (${features.trend}) >= ${trend_min}: Study effort heavily concentrated in final days with increasing intensity.`;
    confidence = features.PI > 0.55 ? 'High' : 'Medium';
  } 
  else if (features.cv <= cv_max && features.std <= std_max) {
    // Consistent: Low variability in study pattern
    pattern = 'Consistent';
    reasoning = `Coefficient of Variation (${features.cv}) <= ${cv_max} AND Std Dev (${features.std}) <= ${std_max}: Study minutes are evenly distributed across all days with low variability.`;
    confidence = features.cv < 0.4 ? 'High' : 'Medium';
  } 
  else {
    // Irregular: Everything else - high variability but not last-minute
    pattern = 'Irregular';
    reasoning = `CV (${features.cv}) > ${cv_max} OR Std Dev (${features.std}) > ${std_max}, but not last-minute pattern: Study pattern varies significantly day-to-day without clear trend.`;
    confidence = 'Medium';
  }

  return {
    pattern,
    features,
    reasoning,
    confidence
  };
}

/**
 * Process all students and add classification
 * @param {Array} students - Array of student objects
 * @returns {Array} Students with classification added
 */
export function classifyAllStudents(students) {
  return students.map(student => ({
    ...student,
    ...classifyStudent(student.days)
  }));
}
