import { extractFeatures } from './featureEngine';

/**
 * Model configuration - thresholds are LEARNED from training data
 * Run model/train.py to generate model_config.json
 * 
 * Classification uses Decision Tree logic trained on K-Means clusters
 */
let MODEL_CONFIG = null;

/**
 * Load trained model configuration from JSON file
 * This is generated by the Python training script - REQUIRED for classification
 */
export async function loadModelConfig() {
  try {
    const response = await fetch('/model_config.json');
    if (response.ok) {
      MODEL_CONFIG = await response.json();
      console.log('Loaded trained model config:', MODEL_CONFIG);
      return true;
    }
  } catch (e) {
    console.error('Failed to load model config:', e);
  }
  return false;
}

/**
 * Check if model is loaded
 */
export function isModelLoaded() {
  return MODEL_CONFIG !== null;
}

/**
 * Classify a student's study pattern based on trained model rules
 * Uses thresholds learned from K-Means clustering + Decision Tree
 * 
 * @param {Array} days - Array of study minutes values
 * @returns {Object} Classification result with pattern, features, and reasoning
 */
export function classifyStudent(days) {
  const features = extractFeatures(days);
  
  // If model not loaded, cannot classify
  if (!MODEL_CONFIG || !MODEL_CONFIG.thresholds) {
    return {
      pattern: 'Unknown',
      features,
      reasoning: 'Model not loaded. Run train.py and copy model_config.json to public folder.',
      confidence: 'None'
    };
  }
  
  const { cv_max, std_max } = MODEL_CONFIG.thresholds.consistent;
  const { pi_min, trend_min } = MODEL_CONFIG.thresholds.last_minute;
  
  let pattern = '';
  let reasoning = '';
  let confidence = '';

  // Decision Tree Classification Logic (thresholds learned from data)
  // Priority: Check for Last-minute first (stronger signal), then Consistent
  
  if (features.PI >= pi_min && features.trend >= trend_min) {
    // Last-minute: High concentration at end + upward trend
    pattern = 'Last-minute';
    reasoning = `Procrastination Index (${features.PI}) >= ${pi_min.toFixed(3)} AND trend (${features.trend}) >= ${trend_min.toFixed(2)}: Study effort heavily concentrated in final days with increasing intensity.`;
    const pi_threshold_high = pi_min + (1 - pi_min) * 0.3;
    confidence = features.PI > pi_threshold_high ? 'High' : 'Medium';
  } 
  else if (features.cv <= cv_max && features.std <= std_max) {
    // Consistent: Low variability in study pattern
    pattern = 'Consistent';
    reasoning = `Coefficient of Variation (${features.cv}) <= ${cv_max.toFixed(3)} AND Std Dev (${features.std}) <= ${std_max.toFixed(2)}: Study minutes are evenly distributed across all days with low variability.`;
    confidence = features.cv < cv_max * 0.7 ? 'High' : 'Medium';
  } 
  else {
    // Irregular: Everything else - high variability but not last-minute
    pattern = 'Irregular';
    reasoning = `CV (${features.cv}) > ${cv_max.toFixed(3)} OR Std Dev (${features.std}) > ${std_max.toFixed(2)}, but not last-minute pattern: Study pattern varies significantly day-to-day without clear trend.`;
    confidence = 'Medium';
  }

  return {
    pattern,
    features,
    reasoning,
    confidence
  };
}

/**
 * Process all students and add classification
 * @param {Array} students - Array of student objects
 * @returns {Array} Students with classification added
 */
export function classifyAllStudents(students) {
  return students.map(student => ({
    ...student,
    ...classifyStudent(student.days)
  }));
}
